name: Nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: "00 01 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger netlify build hook
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK }}
    
